import { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "@Features";
import { NavLinks } from "@Constants";
const Admin: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar links={NavLinks.links} />
    </div>
  );
};

export default Admin;
