import { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Navbar } from "@Features";
import { NavLinks } from "@Constants";
import { Table } from "@Features";
import { TableData } from "dummyData";
import { Button } from "@mantine/core";
import BlogModal from "Features/Blog Modal";

const Admin: NextPage = () => {
  const [isOpened, setIsOpened] = useState(false);
  return (
    <div>
      <Head>
        <title>All Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar links={NavLinks.links} />
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-end",
        }}
      >
        <Button
          mb={"md"}
          style={{ width: "100px" }}
          onClick={() => setIsOpened(true)}
        >
          Create
        </Button>
        <Table data={TableData.data} />
        <BlogModal isOpened={isOpened} setIsOpened={setIsOpened} />
      </main>
    </div>
  );
};

export default Admin;
