import { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "@Features";
import { NavLinks } from "@Constants";
import Editor from "Features/Editor";
const Create: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar links={NavLinks.links} />
      <main>
        <Editor />
      </main>
    </div>
  );
};

export default Create;
